const cities = [
  { city: "Toronto" },
  { city: "Winnipeg" },
  { city: "Halifax" },
  { city: "Montreal" },
  { city: "Vancouver" },
  { city: "Calgary" },
  { city: "Edmonton" },
  { city: "Ottawa" },
  { city: "Mississauga" },
  { city: "Brampton" },
  { city: "Hamilton" },
  { city: "London" },
  { city: "Markham" },
  { city: "Vaughan" },
  { city: "Kitchener" },
  { city: "Windsor" },
  { city: "Richmond Hill" },
  { city: "Burlington" },
  { city: "Oshawa" },
  { city: "Greater Sudbury" },
  { city: "Barrie" },
  { city: "Guelph" },
  { city: "Cambridge" },
  { city: "St. Catharines" },
  { city: "Waterloo" },
  { city: "Thunder Bay" },
  { city: "Brantford" },
  { city: "Pickering" },
  { city: "Niagara Falls" },
  { city: "Peterborough" },
  { city: "Sault Ste. Marie" },
  { city: "Sarnia" },
  { city: "Norfolk County" },
  { city: "Welland" },
  { city: "Belleville" },
  { city: "North Bay" },
  { city: "Brandon" },
  { city: "Dauphin" },
  { city: "Flin Flon" },
  { city: "Morden" },
  { city: "Portage la Prairie" },
  { city: "Selkirk" },
  { city: "Steinbach" },
  { city: "Thompson" },
  { city: "Winkler" },
];

export default cities;
