const cities = [
  { city: "Toronto" },
  { city: "Winnipeg" },
  { city: "Halifax" },
  { city: "Montreal" },
  { city: "Vancouver" },
  { city: "Calgary" },
  { city: "Edmonton" },
  { city: "Ottawa" },
  { city: "Quebec City" },
  { city: "Hamilton" },
  { city: "Kitchener" },
  { city: "London" },
  { city: "Victoria" },
  { city: "Oshawa" },
  { city: "Windsor" },
  { city: "Saskatoon" },
  { city: "Regina" },
  { city: "St. John's" },
  { city: "Greater Sudbury" },
  { city: "Sherbrooke" },
  { city: "Barrie" },
  { city: "Kelowna" },
  { city: "Abbotsford" },
  { city: "Guelph" },
  { city: "Kingston" },
  { city: "Moncton" },
  { city: "Saguenay" },
  { city: "Trois-Rivières" },
  { city: "Chicoutimi" },
  { city: "Saint John" },
  { city: "Peterborough" },
  { city: "Thunder Bay" },
  { city: "Lethbridge" },
  { city: "Nanaimo" },
  { city: "Kamloops" },
  { city: "Belleville" },
  { city: "Charlottetown" },
  { city: "St. Catharines" },
  { city: "Fredericton" },
  { city: "Sarnia" },
  { city: "Chilliwack" },
  { city: "Drummondville" },
  { city: "Red Deer" },
  { city: "Prince George" },
  { city: "Medicine Hat" },
  { city: "New Westminster" },
  { city: "Saint-Jean-sur-Richelieu" },
  { city: "Sherwood Park" },
  { city: "Saint-Jérôme" },
  { city: "Grande Prairie" },
  { city: "Granby" },
  { city: "North Bay" },
  { city: "Blainville" },
  { city: "Cornwall" },
  { city: "Oakville" },
  { city: "Burlington" },
  { city: "Brantford" },
  { city: "Whitehorse" },
  { city: "Yellowknife" },
  { city: "Iqaluit" },
];

export default cities;
