const model = [
    {"model":"GUD24AH2/D-D(U)"},
    {"model":"GUD30AH2/D-D(U)"},
    {"model":"GUD36AH2/D-D(U)"},
    {"model":"GUD42AH2/D-D(U)"},
    {"model":"GUD48AH2/D-D(U)"},
    {"model":"GUD60AH2/D-D(U)"},
    {"model":"GUD36AH2/A-D(U)"},
    {"model":"GUD60AH2/A-D(U)"},
    {"model":"GWH09QB-D3DNB8E/I (WIFI)"},
    {"model":"GWH12QC-D3DNB8E/I (WIFI)"},
    {"model":"GWH18QD-D3DNB8E/I (WIFI)"},
    {"model":"GWH24QE-D3DNB8E/I (WIFI)"},
    {"model":"GWH24QE-D3DNB2R/O (LCLH)"},
    {"model":"GWH24QE-D3DNB8R/I(WIFI)"},
    {"model":"GUD36W/A-D(U)"},
    {"model":"GUD60W/A-D(U)"},
    {"model":"GUD24W2/D-D(U)"},
    {"model":"GUD30W2/D-D(U)"},
    {"model":"GUD36W2/D-D(U)"},
    {"model":"GUD42W2/D-D(U)"},
    {"model":"GUD48W2/D-D(U)"},
    {"model":"GUD60W2/D-D(U)"},
    {"model":"XK76"},
    {"model":"XK19"},
    {"model":"ELEMHT16-5KW"},
    {"model":"ELEMHT16-8KW"},
    {"model":"ELEMHT16-10KW"},
    {"model":"ELEMHT16-15KW"},
    {"model":"ELEMHT18-5KW"},
    {"model":"ELEMHT18-8KW"},
    {"model":"ELEMHT18-10KW"},
    {"model":"ELEMHT18-15KW"},
    {"model":"GFH(09)EA-D3DNA1A/I"},
    {"model":"GFH(12)EA-D3DNA1A/I"},
    {"model":"GFH(18)EA-D3DNA1A/I"},
    {"model":"GFH(21)EA-D3DNA1A/I"},
    {"model":"GFH(24)EA-D3DNA1A/I"},
    {"model":"GKH(12)BB-D3DNA3A/I"},
    {"model":"GKH(18)BB-D3DNA3A/I"},
    {"model":"GKH(24)BC-D3DNA4A/I"},
    {"model":"GWHD(18)ND3GO"},
    {"model":"GWHD(24)ND3GO"},
    {"model":"GWHD(36)ND3GO"},
    {"model":"GWHD(42)ND3EO"},
    {"model":"GWHD(18)ND3MO"},
    {"model":"GWHD(24)ND3MO"},
    {"model":"GWHD(30)ND3MO"},
    {"model":"GWHD(36)ND3MO"},
    {"model":"GWHD(42)ND3MO"},
    {"model":"GCAT36F/NaA"},
    {"model":"GCAT60H/NaA"},
    {"model":"ACI-BCO24CP17"},
    {"model":"ACI-AUO24SHP-M"},
    {"model":"GWH09QB-D3DNA6E/O(LCLH)"},
    {"model":"GWH12QC-D3DNA6E/O (LCLH)"},
    {"model":"GWH18QD-D3DNA6E/O (LCLH)"},
    {"model":"GWH24QE-D3DNA6E/O (LCLH)"},
    {"model":"GWH12QC-D3DNB2M/O(LCLH)"},
    {"model":"GWH12QC-D3DNB8N/I(WIFI)"},
    {"model":"GWH18QD-D3DNB2L/O(LCLH)"},
    {"model":"GWH18QD-D3DNB8L/I(WIFI)"},
    {"model":"GWH09ATCXB-D3DNA1A/O"},
    {"model":"GWH09ATCXB-D3DNA3A/I"},
    {"model":"GWH12ATCXB-D3DNA1C/O"},
    {"model":"GWH12ATCXB-D3DNA3C/I"},
    {"model":"GWH18ATDXD-D3DNA1A/O(LCLH)"},
    {"model":"GWH18ATDXD-D3DNA3A/I"},
    {"model":"GWH24QEXF-D3DNC4C/O(LCLH)"},
    {"model":"GWH24ATEXF-D3DNA3E/I"},
    {"model":"GWH09QC-A3DNA1D/O (LCLH)"},
    {"model":"GWH09QC-A3DNB8D/I (WIFI)"},
    {"model":"GWH12QC-A3DNA1D/O (LCLH)"},
    {"model":"GWH12QC-A3DNB8D/I (WIFI)"},
    {"model":"GWH12QC-A3DNA6E/O"},
    {"model":"GWH12QC-A3DNB8E/I"},
    {"model":"GWH09ACD-D3DNA1A/O(LCLH)"},
    {"model":"GWH09QD-D3DND6B/I(WIFI)"},
    {"model":"GWH12YD-D3DNA1A/O (LCLH)"},
    {"model":"GWH12QD-D3DND6A/I (WIFI)"},
    {"model":"GWH18YE-D3DNA1A/O (LCLH)"},
    {"model":"GWH18QE-D3DND6A/I (WIFI)"},
    {"model":"GWH24YE-D3DNA1A/O (LCLH)"},
    {"model":"GWH24QE-D3DND6L/I ( WIFI)"},
    {"model":"GAE09AE-D3NRNB2G"},
    {"model":"ACI-AUO30SHP-M"},
    {"model":"ACI-CCO36CP21"},
    {"model":"GAA12AE-D3NRNB2G"},
    {"model":"GWH12QC-D3DNB8D/I (WIFI)"},
    {"model":"GWH18QD-D3DNB8G/I (WIFI)"},
    {"model":"ACI-BCO24CP17"},
    {"model":"ACI-AUO24SHP-M"},
    {"model":"ACI-CCO36CP21"},
    {"model":"ACI-AUO30SHP-M"},
    {"model":"GWH09ATCXB-D3DNA3A/I"},
    {"model":"GWH12ATCXB-D3DNA3C/I"},
    {"model":"GWH18ATDXD-D3DNA3A/I"},
]

export default model;
